"""add owner_id to todos and created_by_id to categories

Revision ID: 312759b2f0cc
Revises: 8ac3f40f9360
Create Date: 2026-09-21 14:33:57.189025

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "312759b2f0cc"
down_revision: str | Sequence[str] | None = "8ac3f40f9360"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("created_by_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_categories_created_by_id_users", "categories", "users", ["created_by_id"], ["id"]
    )
    op.add_column("todos", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.create_foreign_key("fk_todos_owner_id_users", "todos", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_todos_owner_id_users", "todos", type_="foreignkey")
    op.drop_column("todos", "owner_id")
    op.drop_constraint("fk_categories_created_by_id_users", "categories", type_="foreignkey")
    op.drop_column("categories", "created_by_id")
    # ### end Alembic commands ###
