"""add_deleted_at_to_todos

Revision ID: 6cd5eca55079
Revises: fdf53369194e
Create Date: 2026-10-01 14:38:57.870571

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6cd5eca55079"
down_revision: str | Sequence[str] | None = "fdf53369194e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todos", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todos", "deleted_at")
    # ### end Alembic commands ###
