"""add_deleted_at_and_drop_unicity_for_name_to_categories

Revision ID: bcaa0bbcdef2
Revises: 6cd5eca55079
Create Date: 2026-10-01 15:29:44.932764

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bcaa0bbcdef2"
down_revision: str | Sequence[str] | None = "6cd5eca55079"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f("uq_categories_name_lower"), table_name="categories")
    op.create_index(
        op.f("uq_partial_categories_name_lower"),
        "categories",
        [sa.literal_column("lower(name)")],
        unique=True,
        postgresql_where=sa.literal_column("deleted_at IS NULL"),
        sqlite_where=sa.literal_column("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("uq_partial_categories_name_lower"), table_name="categories")
    op.create_index(
        op.f("uq_categories_name_lower"),
        "categories",
        [sa.literal_column("lower(name)")],
        unique=True,
    )
    op.drop_column("categories", "deleted_at")
    # ### end Alembic commands ###
