"""make owner_id and created_by_id not null

Revision ID: e073da9b8a87
Revises: 9e90d89d433e
Create Date: 2026-09-21 15:12:56.605657

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e073da9b8a87"
down_revision: str | Sequence[str] | None = "9e90d89d433e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("categories", "created_by_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("todos", "owner_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("todos", "owner_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("categories", "created_by_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
