"""users_unicity

Revision ID: fdf53369194e
Revises: 9251abfc77b1
Create Date: 2026-09-25 12:27:40.556839

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fdf53369194e"
down_revision: str | Sequence[str] | None = "9251abfc77b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_categories_created_by_id"), "categories", ["created_by_id"], unique=False
    )
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=False)
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_pseudo"), "users", ["pseudo"], unique=False)
    op.create_index(
        "uq_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_index(
        "uq_users_pseudo_lower", "users", [sa.literal_column("lower(pseudo)")], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_users_pseudo_lower", table_name="users")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_index(op.f("ix_users_pseudo"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index(op.f("ix_categories_created_by_id"), table_name="categories")
    # ### end Alembic commands ###
